stages:
  - build
  - deploy

variables:
  FRONT_VERSION: v1.0.0

build_front:
  stage: build
  image: docker
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    PROJECT_ENV_FILE: .env.production
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo $IMAGE_NAME
    - docker build . -f Dockerfile --tag $IMAGE_NAME
    - docker push $IMAGE_NAME
  tags:
    - app2
  only:
    refs:
      - main

deploy_front:
  stage: deploy
  image: docker
  only:
    refs:
      - main
  when: manual
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    PROJECT_ENV_FILE: .env.production
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo $IMAGE_NAME
    - docker pull $IMAGE_NAME
    - docker pull "$IMAGE_NAME"
    - docker rm -f panta_front 2>/dev/null || true
    - docker compose -f docker-compose.yml down --remove-orphans || true
    - docker compose -f docker-compose.yml up -d
  tags:
    - app2

build_dev:
  stage: build
  image: docker
  variables:
     IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
     PROJECT_ENV_FILE: .env.development
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo $IMAGE_NAME
    - docker pull docker.arvancloud.ir/node:20-alpine
    - docker build --build-arg PROJECT_ENV_FILE=.env.development -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  tags:
    - app5
  only:
    refs:
      - version1

deploy_front_dev:
  stage: deploy
  image: docker
  only:
    refs:
      - version1
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    PROJECT_ENV_FILE: .env.development
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo $IMAGE_NAME
    - docker pull docker.arvancloud.ir/node:20-alpine
    - docker pull $IMAGE_NAME
    - docker pull "$IMAGE_NAME"
    - docker rm -f panta_front 2>/dev/null || true
    - docker compose -f docker-compose.yml down --remove-orphans || true
    - docker compose -f docker-compose.yml up -d
  tags:
    - app5
